name: Build and Deploy
on:
  push:
    branches:
      - main  # 또는 메인 브랜치에 따라 변경 test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'  # 프로젝트에 맞는 Node.js 버전 지정
    - run: npm install
    - run: npm run build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
